### PR TITLE
Typo/test

### PR DESCRIPTION
**Pull request by umahaea**
Add all the tests for typography component.

### CODE REVIEW

**Comment by umahaea** [comment]
@dstack and @StommePoes - please review my PR for the typography tests..

**Comment by dstack** [comment]
looks good.  Had one question regarding the exact match of css properties, since thing like font-weight can get "hidden" a bit by some layout engines, and transformed from "300" to "light" and vice-versa, but you appear to be handling that case.  Well Done.

**Comment by StommePoes** [comment]
300 Should go to "normal" for fonts like Arial (which all the Windows machines and most Linuxes will show anyway) who don't come in a range of weights. I think the Open Sans is supplied to the browser as a pack of weights, do you know of an engine that doesn't follow correctly when weights are actually supplied?

**Comment by dstack** [comment]
@StommePoes 
I misread and then went to test my statement and couldn't identify one, so we'll say it's IE < 7 and leave it at that. :smile:

**Pull request merged**
