### PR TITLE
Add new typography styles for lists

### PR DESCRIPTION
**Pull request by gayankumara**
added list ordered/unordered and related unit test, remove in line list

### CODE REVIEW

**Comment by StommePoes** [comment]
feedback:
Wherever there's "loose text" that's around HTML elements (like text before and after a list), those ought to be in &lt;p&gt; tags generally.

A few times there is "exams,without" (missing space between words).

For the ordered lists, even though we're using the classes to make the ordering (using pseudo-elements so Parker can ensure they line up correctly), if it's an ordered list, we also need to use the &lt;ol&gt; tag and not the &lt;ul&gt; tag. Assistive technology can recognise the tag type.

I would change the first instance of this text ("Nested lists
When nested, styled-lists--ordered should be added to each &lt;ul&gt; element.")
to
"Nested **ordered** lists
When nested, style-lists--ordered should be added to each **&lt;ol&gt;** element.") 

And the second one to 
"Nested unordered lists
When nested, styled-lists--unordered should be added to each &lt;ul&gt; element."

So people know which example is which.

Finally maybe they should be switched since the very first example is

Unstyled lists
Use pe-list--unstyled for plain lists.

That way it starts with "plain" (unordered) lists and then can move to the ordered/numbered lists.

**Comment by StommePoes** [comment]
Hi,
in the example in typography.md with ordered lists, the code example is showing unordered lists:
`<ul class="pe-list styled-lists--ordered">
   <li>List item one. How are you doing today? Quite fine, thank you.</li>
   <li>Item two.</li>
   <li>Item three.</li>
     <ul class="pe-list nested-styled-lists--ordered">
       <li>child item one</li>
       <li>child item two</li>
       <ul class="pe-list pe-list-nested--ordered">
         <li>grand child item one</li>
         <li>grand child item two</li>
       </ul>
 </ul>`
Also, we can't have ul's as direct children of ul's (nor ol's of ol's)-- only li's are allowed per the spec to be direct children of ul's or ol's.
It would have to be more like this
```
<ol class="pe-list styled-lists--ordered">
   <li>List item one. How are you doing today? Quite fine, thank you.</li>
   <li>Item two.</li>
   <li>Item three.</li>
   <li>
     <ol class="pe-list nested-styled-lists--ordered">
       <li>child item one</li>
       <li>child item two</li>
       <li>
         <ol class="pe-list pe-list-nested--ordered">
           <li>grand child item one</li>
           <li>grand child item two</li>
         </ol>
       </li>
    </ol>
</li>
</ol>
```

same goes for the ordered list under the headings.

**Comment by gayankumara** [comment]
Hi,

Thank you very much for feedback with updated how it would be.
I will update and pull request ASAP.

**Comment by StommePoes** [comment]
Hey don't forget to update your local v0 branch and in your branch, git rebase -i v0 to get your stuff up to date-- then I can just merge it.

**Pull request closed without merging**
