### PR TITLE
adding bookmark icon from font awesome

### PR DESCRIPTION
**Pull request by dhmen**
This is a requirement for etextHE group.

### CODE REVIEW

**Comment by StommePoes** [comment]
Looks good to me and verified I see all the icons including the new ones.

**Comment by wyseguyonline** [comment]
I'm good with it as well.  Assuming that design (i.e. @parkerpearson ) has signed off on these.

**Comment by parkerpearson** [comment]
Component modifications should generally be proposed and discussed on the [mailing list](https://groups.google.com/a/pearson.com/forum/#!forum/elemental-discuss/categories) before being implemented.

@dhmen can you or the designer working on this post these to the list just to make sure your usage matches up with how other products are treating these icons?

**Comment by dhmen** [comment]
Thanks for the quick response.

@parkerpearson, I am new to the group.. so not familiar with the processes. I am in the process of touching base with the designers.

thanks!

**Comment by parkerpearson** [comment]
@dhmen sure, no worries. Let me know if you have any other questions.

**Pull request closed without merging**
