### PR TITLE
feat(icons): Add ico mover script; adjust readme; add Hung's bell icon

### PR DESCRIPTION
**Pull request by StommePoes**

### CODE REVIEW

**Comment by StommePoes** [comment]
@umahaea This adds a script to make some things a little easier, and expands the readme file.

- script should fail if no argument given
- script should fail if argument is not a xxx.zip file in name

Maybe I need more checks?

**Comment by umahaea** [comment]
@StommePoes - would be great if you could walk me through the logic of the script.

**Comment by StommePoes** [comment]
I was not able to rebase this one... it simply failed at a commit and would not tell me why.

**Comment by umahaea** [comment]
@StommePoes - After executing the last step in 'how_to_add_icon.md' update _/scss/_icons.scss with the new style._ , how do I cross check if the icon is successfully added or not?

**Comment by StommePoes** [comment]
if you actually add an icon, you need to add the HTML (to icons.md) and css (to scss/_icons.scss) and check in the browser.

Or, check the time stamps on the new fonts-- this at least lets you know you have newer font files.

**Comment by umahaea** [comment]
This looks good to me.

**Pull request merged**
