### PR TITLE
bug fix in text input mobile test.

### PR DESCRIPTION
**Pull request by gayankumara**
bug fix for Box shadow in text input , related to mobile testing.

### CODE REVIEW

**Comment by gayankumara** [comment]
This branch is 1 commit ahead of v0. 
There is Travis failure.  
but one of the is passed.  (continuous-integration/travis-ci/push — The Travis CI build passed)

**Comment by gayankumara** [comment]
closed and opened pull request, now seems, it passed through Travis.. :+1:

**Comment by StommePoes** [comment]
Hey Gayan-- could you put this in the mixins that pe-input use, the way we did for the placeholder?

The mixins because it's a "vendor prefix" which our current linting dislikes, but also because we will probably have in the future input type=url and input type=email etc and we also want them to have this fix too!

Thanks

**Comment by gayankumara** [comment]
moved -webkit-appearance: none, into  pe-input in mixins.

**Pull request merged**
