### PR TITLE
feat: re-structured SCSS folders for v1

### PR DESCRIPTION
**Pull request by davodey**
the re-structure allows for more modular SCSS that will have less dependancies

### CODE REVIEW

**Comment by StommePoes** [comment]
You ought to run this locally as well: `npm start` and go to localhost:3000

Only some of the scss files are being dumped into the docs.css file, possibly because of the file path changes and the gulpfile doesn't know about them. The gulpfile needs to be updated with the new file paths. 

I think this is why the build is failing. The CSS is being checked in Travis by our UX Test Platform and it's measuring mismatches simply because not all the CSS is there.

**Comment by StommePoes** [comment]
Oh, that was on purpose. So, this only needs code review and should not need any QA, as there's technically nothing here for QA to QA.

**Comment by JasonLantz** [comment]
looks good to me....

**Comment by wyseguyonline** [comment]
LGTM

**Comment by StommePoes** [comment]
@umahaea after the colours get added. So currently in this PR, only the unchanged things (resets, styles for the elements-surge page) are being generated. So there is currently nothing to QA, and when colours is PR'd only the new colours will be run through tests. So I think we'll have a separate set of tests for v1 because all the styles are changing anyway for rebranding.

**Pull request merged**
