### PR TITLE
Des 668

### PR DESCRIPTION
**Pull request by StommePoes**
1. Added links to design/redlines pages
2. Added screenshot (had to link to our docs repo) showing checkmarks are not part of the select redesign style
3. Restructured headings in inputs; other doc adjustments.

### CODE REVIEW

**Comment by umahaea** [comment]
@StommePoes - Ran regression against this branch: https://travis-ci.org/Pearson-Higher-Ed/ux-test-platform/builds/239643862
Notice few failures on the disabled tests. We can discuss when u are back to work.

**Comment by StommePoes** [comment]
@umahaea @udhadpa can we put this through QA and merge? I'll see where it went on the Jira board.

**Comment by StommePoes** [comment]
I just updated this to v1... it *should* pass all tests. If so, can it be merged? It's mostly a documentation thing anyway (it also removed the disabled-label-style which I think has been added to v1 by now anyway)

**Comment by StommePoes** [comment]
okay, I think this is ready to be merged. @udhadpa @umahaea  \o/

**Comment by udhadpa** [comment]
Regression test passed - https://travis-ci.org/Pearson-Higher-Ed/ux-test-platform/builds/266936530
Good to merge

**Pull request merged**
