### PR TITLE
Des 211

### PR DESCRIPTION
**Pull request by allas**
Add Check Boxes to the Inputs component in ElementsSDK 

@aaronkaka , @StommePoes , @umahaea

### CODE REVIEW

**Comment by StommePoes** [comment]
Hi!
Feedback:
1. I don't think we want 10px margin all around the checkbox... just on the right side to push the label away. If a developer wants to "indent" the radios/checks, they can do that with padding on the fieldset they're in. But now, if they want the checkboxes to align perfectly left, they won't-- they'll be in 10px.
2. We definitely don't want the left: -999.... that's a leftover.

It otherwise looks good, except I saw that the headings in markdown (checked, unchecked, etc) are h3's and they should be h2's (because we don't want to skip heading levels on a page). The color page does this too but most of the others seem to do it right. So I'll ask a favour of you: could you also change the next heading in the Colors page to an h2 as well?

**Comment by StommePoes** [comment]
What does the class "pe-lbl-chk" do?

**Comment by allas** [comment]
I've added that for texting the label properties.

**Comment by StommePoes** [comment]
I'm going to get Gayan's changes in and then I'll look at yours!

**Pull request merged**
