### PR TITLE
feat(icons): started adding some new icons

### PR DESCRIPTION
**Pull request by StommePoes**
@stommepoes hey not all these icons are cool man

### CODE REVIEW

**Comment by umahaea** [comment]
@StommePoes - do u mind sharing the unicodes for the newly added icons in this PR? I will add tests to them immediately.

**Comment by StommePoes** [comment]
http://jira.pearsoncmg.com/jira/browse/DES-354 lists the icons added, times-circle was removed.

unicodes:
times-circle-o: \f05c
heart: \f004
heart-o: \f08a
laptop: \f109
book: \f02d
list-ul: \f0ca
th-large: \f009
newspaper-o: \f1ea
video-camera: \f03d
picture-o: \f03e
suitcase: \f0f2
caret-right: \f0da
caret-bottom: \f0d7
lightbulb-o: \f0eb

**Comment by StommePoes** [comment]
I assume these are failing because of the icons tests... if not, let me know if a test outside icons has failed.

**Comment by umahaea** [comment]
@StommePoes - the one icons test that failed is: pe-icon--times-circle, since this is updated to .pe-icon--times-circle-o. I will fix the test and add the new icons to the test. Good that our tests catches these minute issues too and notify the elements sdk failure upfront :)

**Comment by umahaea** [comment]
Looks good to me Mallory. Added tests for new icons, and fixed the broken test for pe-icon--times-circle and updated it with pe-icon--times-circle-o.

**Pull request merged**
