### PR TITLE
add info icons

### PR DESCRIPTION
**Pull request by wyseguyonline**
Adding two info icons and modify documentation.

### CODE REVIEW

**Comment by StommePoes** [comment]
The actual icons need to be added as well (apparently we only keep just the ones we need instead of making the user DL the whole font), and also the tests in /test/spec/icons.js and test/fixtures/icons/icons.html

**Comment by wyseguyonline** [comment]
Any recommended sites for how to add the icons to the fonts?  Would save me more than a little research into that.

**Comment by StommePoes** [comment]
Actually we're discussing that right now. It's a bit of an involved process and it also turns out Design has to ok them (in this case they're probably ok). Stay tuned, either I or Aaron will work with you on this.

**Comment by wyseguyonline** [comment]
Ok.  FYI, I am adding three additional icons as well for another Console team member.

**Comment by StommePoes** [comment]
Hm, good to know... we need to get Parker involved.

**Comment by StommePoes** [comment]
This is what I'm adding to /misc/icomoon/readme.md (in the same directory is selection.json):

Go to the IcoMoon app (https://icomoon.io/app).

You can import *selection.json* back to the IcoMoon app using the *Import Icons* input (or via Main Menu → Manage Projects) to retrieve your icon selection. It'll be called "icomoon" even though we're using Font-Awesome. If only IcoMoon icons are shown on the page, scroll down to the link "Add Icons from Library" and choose Font-Awesome ("Add" button).

To select from Font-Awesome, make sure the "select" button at the top of the page is selected (it looks like a mouse arrow in a box, has an invisible name of "select") and click on icons you'd like to add. Selected icons get an orange border and white background. Then go back to your "icomoon" group and click the stripey bar (button with the invisible name of "Menu") to show a submenu. With only your new icons selected, choose "Copy selection to set", then make sure all the icons in your "icomoon" group are selected. The sticky menu at the bottom of the screen has a link "Generate Font" which will give you both new font files and a new selection.json.

It's very easy to accidentally double your current icons when using "Copy selection to set" :/

Anyway, this and the typo fix you have in the test page for pe-icon--file will make this ready to merge, but we need an ok from Parker or someone.

**Comment by wyseguyonline** [comment]
Font changes apparently put this in conflict.

**Comment by StommePoes** [comment]
The chevrons were asked for the o-assignment thingie so we had a story on that already so I'd already done that.
I pull the master branch (v0) before committing stuff to make sure I'm up to date. Then a rebase my branch to v0. Avoids conflict fairly well.

**Comment by wyseguyonline** [comment]
Closing pull request.  Started over after pulling from upstream.

**Pull request closed without merging**
