### PR TITLE
fix(inputs): give explicit focus styles to input/textarea, focussed e…

### PR DESCRIPTION
**Pull request by StommePoes**
…rror states

@umahaea 
inputs and textareas have a focus style
`outline: 0;` 
`border: 1px solid #0d65a6;`
`box-shadow: 0px 0px 4px #0d65a6;`

inputs, textareas, and selects in an error state now have
`border: 1px solid #d0021b;`

and errors in focus have
`box-shadow: 0px 0px 4px #d0021b;`

### CODE REVIEW

**Comment by umahaea** [comment]
@StommePoes - checked this one manually. Automated tests in progress. You can merge this one.

**Comment by umahaea** [comment]
@StommePoes - sorry I take back my word. I noticed couple of differences in Windows 10 - IE/Edge/Firefox

image

All other browsers and Mobile(iOS and Android looks good.)

**Comment by StommePoes** [comment]
The heights for textareas aren't set in the design, actually, only the labels' heights. The height of a textarea can be set by either using the rows attrbute (which will give different results cross-browser) or by setting a height in CSS.  Though for the same data, those FF/IE differences look pretty big. Possibly IE adds more inner room...

**Comment by umahaea** [comment]
@StommePoes - Thanks and how about the box-shadow IE/Edge focus state, the color is returned as hex value. Is this expected?

**Comment by StommePoes** [comment]
I don't know why IE/Edge does this. However, it is certainly equivalent to any rgb versions we are testing (meaning, those are the correct colours and hex is a valid way of stating box-shadow). I should think the test should be able to include the equivalents and pass those.

**Comment by umahaea** [comment]
Thanks @StommePoes.. So TextArea tests are done. @veerabvm is working on Select and Inputs focus styles tests. Once he is done, we can merge this PR to V0.

**Pull request merged**
