### PR TITLE
feat: add responsive templates

### PR DESCRIPTION
**Pull request by JasonLantz**
update to pe-template__double > :first-child from pe-template__double  :first-child

add link to design page in docs....

### CODE REVIEW

**Comment by StommePoes** [comment]
Do you need >? That's quite specific. I just worried about, does anyone today see blah :first-child as something different from blah:first-child (no space before colon).

**Comment by wyseguyonline** [comment]
Looks ok to me.  I'd prefer too specific over too broad.

**Comment by StommePoes** [comment]
I had missed the ```div[class=".foo"]``` stuff but Payal had caught it, tried a fix but had some issues merging/rebasing so I hope I didn't lose anything.

**Comment by udhadpa** [comment]
Code is verified manually. Tests have been fixed.
Merging the branch

**Pull request merged**
