### PR TITLE
Added features for CODE in typography 

### PR DESCRIPTION
**Pull request by isuraamara**
Features and unit tests added

### CODE REVIEW

**Comment by StommePoes** [comment]
Hi,
feedback: The new pe-code mixin you made can be added to the tags themselves in _plain-tags.scss. This is a file that Parker and others can comment out before the sass build if they don't want plain tags to be styled, but only want access to classes.

So you can do 
pre,code {
@import pe-code;
}
or similar.

The block code is missing the 4px horizontal padding from Parker's redlines.

Everything else seems okay.

**Comment by isuraamara** [comment]
Hi,
Thanks  for the feedback.
 Horizontal padding for inline code and kbd was there. Is this required for the pe-code (Block code) ?

**Comment by StommePoes** [comment]
I thought it was, yeah. Let me check again.

**Comment by StommePoes** [comment]
Now I don't see it mentioned anywhere on http://pearson-higher-ed.github.io/design/c/typography/

**Comment by isuraamara** [comment]
Once we add pe-code to plain_tags our documentation <CODE> will be changing in ugly way. Shall I change documentation <CODE> to use pe-code-inline
pre,
code {
  @include pe-code;
}
Please see below screenshot.

screenshot from 2016-04-06 17 16 09

**Comment by StommePoes** [comment]
Ok, I think for now we don't add the styles to the plain tags. The Elements pages have syntax highlighting, which is what looks bad with the dark background. Since it hasn't been decided if future <code> blocks will have syntax highlighting, just keep it as you had (as a class).

See if you can update your branch and push. It might fail Travis (they've started failing a day or so ago), so if Travis fails, switch to just having a feature branch from our Elements repo directly instead of a fork. Put these changes in your branch and send a PR.

I just heard that now Laxapana has access to our elements repo and that they now prefer that you guys just use branches instead of forks.

**Pull request merged**
