### PR TITLE
Basic body changes

### PR DESCRIPTION
**Pull request by yasithadinesh**

### CODE REVIEW

**Comment by StommePoes** [comment]
Do we close this one? Looks like the other PR has the same list-related changes.

**Comment by yasithadinesh** [comment]
We are still working on basic body, there are few new changes in design specification under basic body, once it is done we will rebase all commits

**Comment by StommePoes** [comment]
Ok, I've reviewed this and have lots of questions!

`<p class="pe-body-paragraph">` is this a special paragraph from other paragraphs? I'm not entirely certain, but I thought, looking at <a href="http://pearson-higher-ed.github.io/design/c/typography/">Parker's page</a> that his styles for p's were just for any p's. If so, instead of mentioning the body in the class name, we would just call it "pe-paragraph". The class styles would be set in the _typography.scss by calling the pe-paragraph mixin from mixins.
Then, to allow authors like Parker who sometimes get Markdown and can't always add a class to an element, we add the styles to any p's without classes in the _plain_tags.scss. I made that file so Parker and others who get HTML they can't add classes to can comment that one out, so they only get mixins and class names. That way they can make their own CSS classes and call the mixins themselves.

I didn't choose it, but the team uses BEM as the method for writing class names. So far as I know, we're copying the rules from the Origami components: https://origami.pearsoned.com/docs/syntax/scss/#specificity
So for the small body text, we would name the class "pe-body--small".

I'm not certain if we want the body and body small tags on the actual body, or let them be classes to go on anything a consuming developer thinks is body-text (copy/ordinary text on a web page with no special role).

**Comment by StommePoes** [comment]
Okay I talked with Parker. He only cares that there is a way for a developer using Elements to be able to style whatever they consider "body text" (plain web page text). So all we need is a class with the styles he's mentioned for regular and small text, and the example code on typography.md should probably be a div or some other large container.

I think body text was already done earlier and is called pe-copy. Is that the same? If they're the same, we only need the pe-copy--small style and a pe-paragraph (simpler than pe-body-paragraph) with the margin.

So how we do this (sorry we're still making the documentation!), we would make a mixin, have a class like pe-paragraph which calls that mixin in _type.scss, and then in _plain_tags.scss set that same mixin to the p.  We would do the same for the body. The work that was done on the headings styles is done in this way. 
So your classes, instead of being like this in _body.scss:
`.pe-body {
   font-size: $pe-body-font-size;
   line-height: $pe-body-line-height;
   color: $pe-body-font-color;
 }`
Since the body styles are under Parker's "Typography" page, I recommend you take the stuff in _body.scss and just place them in the _type.scss file instead. No need for a separate file in this case.
...so would go to _type.scss and state the mixin like
`@mixin pe-body { 
   font-size: $pe-body-font-size;
   line-height: $pe-body-line-height;
   color: $pe-body-font-color;
}
then further down the _type.scss file
.pe-body {
 @include pe-body;
}
(and again, I think these styles might already be covered in the existing "pe-copy" so if they are indeed the same, change "body" to "copy" in the small style and add it to under pe-copy)

and then in _plain_tags.scss, same for body
body {
@include pe-body;
}
Your body testing page in fixtures/type is ok, and your tests look good.

I would use a &lt;div&gt; or similar for the pe-body--small class example, so developers can see a way they could use it. I don't expect they will put the class on the body tag, but on a specific area.

If you keep the paragraph example with the class, state in the text that the class isn't needed by default. The class is more of a weapon for developers who find a paragraph which isn't getting the styles and they need to manually add them.

**Comment by StommePoes** [comment]
Closing this because Gayan took over.

**Pull request closed without merging**
