### PR TITLE
feat: three column template

### PR DESCRIPTION
**Pull request by Sauravvaidya**

### CODE REVIEW

**Comment by umahaea** [comment]
@Sauravvaidya  - We need tests for this PR. Pls ask your QA to add them into "ux-test-platform".

**Comment by kiranmohare23** [comment]
https://travis-ci.org/Pearson-Higher-Ed/ux-test-platform/builds/230441008

**Comment by umahaea** [comment]
@Sauravvaidya  - tests are written and reviewed and the green build url is also shared here(https://travis-ci.org/Pearson-Higher-Ed/ux-test-platform/builds/230441008). Please go ahead and update this branch and merge.

**Comment by umahaea** [comment]
got enough approvals. merging it.

**Pull request merged**
