### PR TITLE
change $ to * in attribute selector for buttons sizing, appended clas…

### PR DESCRIPTION
**Pull request by JasonLantz**
…ses break style

### CODE REVIEW

**Comment by StommePoes** [comment]
Changes look good.

**Comment by wyseguyonline** [comment]
lgtm

**Comment by StommePoes** [comment]
Actually, could we use this PR to add some other stuff?
We don't seem to have the placeholder styles, which were done in the v0 branch with a mixin:
```
@mixin pe-placeholder {                                                         
  &::-webkit-input-placeholder { @content }                                     
  &::-moz-placeholder { @content }                                              
  &:-moz-placeholder { @content }                                               
  &:-ms-input-placeholder { @content }                                          
} 
```
then pe-placeholder was added to pe-inputs, not sure how this best works with the new setup, I can barely read the above and the new sass goes mostly above my head.

Placeholders have a colour and variant (italics), not sure if they have a special font size. Meanwhile we have something in variables called input-placeholder and those look like the correct values for the input *value* (not the placeholder). I think those should be renamed.

Should this be done in this PR or a separate one? Since this is also about inputs, this might be nicer.

**Comment by umahaea** [comment]
looks good..

**Pull request merged**
