### PR TITLE
Add Select box style and documantation

### PR DESCRIPTION
**Pull request by isuraamara**
GCAPI-1046

### CODE REVIEW

**Comment by StommePoes** [comment]
Since you have to update your branch anyway (for Aaron's Travis fix), also do this:

a select is a type of input, so we want to have it with the other inputs. So could you move select-box to the inputs.md page instead?

Also, the select can inherit a lot of properties from pe-input. For example
```
  @include pe-select(
     $pe-select-padding-left,
     $pe-select-padding-right,
     $pe-select-border,
     $pe-select-bg,
     $pe-select-text,
     $pe-select-font-size,
     $pe-select-line-height,
     $pe-select-border-radius
```

Many of these are the same as pe-input, so you do not need new variables only for pe-select, you can call pe-input variables. The text-align is normally default to 'left' in browsers so I do not believe we need to state it here.

**Comment by StommePoes** [comment]
Some notes:

When I tried to `npm start` this, it would not run. There was a metalsmith parse error: we have a missing closing /demo tag after the "error" select.

1. like all inputs, select examples in the md should have labels with them.
Because the label styling depends on the type of input (with single-line inputs, the label is a block; with radio buttons/checkboxes, the label is inline-block), we have been wrapping the inputs in a div, placing the styles on the div, so the code will say
```
.pe-input { //this class is on a div
  & input {
   styles for the input;
 }
 & label {
  styles for the label;
}
&.pe-input--small  input {
 make smaller
}
}
```
or similar. I do this so I can say "for this kind of input, I want this style also on the label". It does make the CSS a little more complicated, I know. But to keep labels with their inputs, and also with their selects, I've wrapped label-input pairs in divs and put the classes on the divs instead of the inputs.

2. Why is the small select dark? In Parker's designs it should look the same as regular select, except smaller.

3. With single-line inputs, we have pe-input class (for most styles) then another class added for other things (pe-input--small is just small, pe-input--readonly is just readonly background colour). I would like to keep this for the selects. So developers who want to use our select but also want to make it small need to add a class. 

Also the "special" part of the name has a -- in it. This would make it "pe-select--small" to make a small select.

The rest looks good.

**Comment by isuraamara** [comment]
Some text-input changes (Error focus color change,in chrome it shows in magenta color) , we decide to do it in another user story . Your suggestions are welcome

**Comment by StommePoes** [comment]
Looks brilliant! If the update to v0 works (it should) I can merge.

**Pull request merged**
