### PR TITLE
docs: added more to README, added most of README to the main Elements…

### PR DESCRIPTION
**Pull request by StommePoes**
… page
@JasonLantz @wyseguyonline @umahaea 

I added more specifics on commenting out unwanted styles, how to add new-component docs (for Greg's team), and now the surge URL (after next release) will have useful info.

@antelopb also curious if you think the README additions are helpful.

I prolly accidentally a typo'd somewhere though.

### CODE REVIEW

**Comment by wyseguyonline** [comment]
approved

**Comment by umahaea** [comment]
Looks ok to me. We need this story to be in our jira board.

**Comment by StommePoes** [comment]
I don't know how to put it on our board, I can only reach the actual Jira page.

**Comment by JasonLantz** [comment]
looks good to me...

**Pull request merged**
