### PR TITLE
updated icons.  Also updated readme to make it easier to follow

### PR DESCRIPTION
**Pull request by loahou04**
new icon f187

### CODE REVIEW

**Comment by StommePoes** [comment]
Note: new "archive" icon is already pre-approved for the notifications drawer (Albert Christy)

bullets-doc looks good.

**Comment by StommePoes** [comment]
@umahaea add test for icon?

**Comment by umahaea** [comment]
yes I will add a test for this new icon.

**Comment by StommePoes** [comment]
@loahou04 While we're waiting for the Ux-framework testing to update to master, before I update this branch, I need you to amend the commit message to follow commitizen-styles (our commits write a lot of our documentation) https://github.com/commitizen/cz-cli

**Comment by StommePoes** [comment]
@loahou04 also, the last steps need following if you add an icon: icons.scss and icons.md (so others can see there is now an archive icon)

**Pull request merged**
