### PR TITLE
Des 468 - Update Color component with v2.0.0 of design document

### PR DESCRIPTION
**Pull request by whatevers**
Updating the Color component. Removed the function to make referencing colors simpler and faster.

### CODE REVIEW

**Comment by wyseguyonline** [comment]
Other than Mallory's observation above, this looks ok to me.

**Comment by StommePoes** [comment]
only final comment is that maybe, like Greg's PR for colours, it should only have the new-style stuff uncommented. So here, only typography, and in my PR, typography, colours, icons.

**Comment by whatevers** [comment]
@StommePoes, @wyseguyonline - Updates made

**Comment by StommePoes** [comment]
looks good

**Comment by umahaea** [comment]
since it is jus scss variables.. we cannot test these variables using selenium.. just manual check is what I could do.. I cross checked it with the design spec and they look good to me.. so there is no additional testing for this PR..

**Pull request merged**
