### PR TITLE
feat(inputs): add new CSS class for fake buttons

### PR DESCRIPTION
**Pull request by StommePoes**
Since it was decided by Design that the datepicker would only look like the search-style inputs but actually was only a picture of a button, we need new styles for this.

### CODE REVIEW

**Comment by wyseguyonline** [comment]
looks ok to me

**Comment by StommePoes** [comment]
Updated-- some id's were being repeated, and now datepicker shows a calendar : P

**Comment by wyseguyonline** [comment]
still looks ok

**Comment by StommePoes** [comment]
@umahaea this still needs some QA added but not sure what yet. We know it has to look like the 'Input with button' from https://pearson-elements-v0.surge.sh/elements/inputs/ except have a focus ring around the whole thing. The part with the calendar does not need QA currently, that's just for people to see it's a datepicker.

**Comment by StommePoes** [comment]
Added small version since we have a small version of the inputs in general.

**Comment by StommePoes** [comment]
It appears the search "button" is a fake button in the Type-Ahead instance as well:
http://pearson-higher-ed.github.io/design/c/type-ahead/beta/

**Pull request closed without merging**
