### PR TITLE
feat(ci-test): Run tests against feature branch in CI

### PR DESCRIPTION
**Pull request by umahaea**
Add more info to the Travis API that will trigger ux-test-platform's elements_sdk test suite only.
And export feature branch name to ux-test-platform, that way the tests point to feature_branch of elements only.

### CODE REVIEW

**Comment by umahaea** [comment]
@StommePoes @wyseguyonline @JasonLantz @aaronkaka for your review.

**Comment by JasonLantz** [comment]
Looks good....

**Comment by StommePoes** [comment]
Seems ok to me.

**Comment by wyseguyonline** [comment]
All good

**Pull request merged**
