### PR TITLE
feat(responsive utilities): add responsive utilities

### PR DESCRIPTION
**Pull request by aarmour**
@dstack

Add breakpoints, media query mixin, and visibility helper classes,
including accessibility helpers.

### CODE REVIEW

**Comment by dstack** [comment]
is there thumbs up emoji for github?  cause I would use the crap out of that.

looks good

**Comment by aarmour** [comment]
@dstack There is: :+1:

**Comment by aarmour** [comment]
Also handy is :beer: and :beers:

**Comment by dstack** [comment]
Github: "the difference between 'beer' and 'beers' is the 's'"

:+1: github

**Pull request merged**
